### ISSUE TITLE
Add a flag to set the connection count or reduce logging spam

### ISSUE THREAD

**Issue by alextes** [kaichaosun/rlt#9]
This is kinda subjective, perhaps we can wait and see if others agree, but I expect most users need just one proxied connection as they're doing development, where a flag to overwrite the connection count could be helpful, I'm guessing you yourself had a need for more connections for example.

**Comment by kaichaosun** [comment]
Yeah, have a configurable flag to set the max connection makes a lot sense. Have the default connection count set to be the one from localtunnel server seems better to make client and server consistent.

**Comment by alextes** [comment]
@kaichaosun by the way, I'm in no hurry for this to work! I just switched to using tunnelto, works well, but also costs money. I'd love for a solid rust tunneling library to exist to help devs. So I thought I'd still report what I'd need to be able to use this instead of other tools, but paying $2 / month for tunnelto is no big deal either in the meantime.

RE: default matching the localtunnel server, that makes total sense! 👍
